### ISSUE TITLE
Can't access the ScrollView Component created in Content Component

### ISSUE THREAD

**Issue by th3no0b** [GeekyAnts/NativeBase#105]
Using a `<Content />` component renders a ScrollView but I can't seem to access that ScrollView in order to call functions like `scrollTo(0)`.

Maybe I'm missing something?

**Comment by himanshu-sahusoft** [comment]
`Content` now renders [`KeyboardAwareScrollView`](https://github.com/APSL/react-native-keyboard-aware-scroll-view) instead of RN `ScrollView`. Use [this](https://github.com/APSL/react-native-keyboard-aware-scroll-view#programatically-scroll-to-any-position) instead of `scrollTo(0)`. We'll soon add this to our docs.

**Comment by sankhadeeproy007** [comment]
![scrollview](https://cloud.githubusercontent.com/assets/10998047/18988163/fd8dfda8-8722-11e6-94fa-42e7e88a3981.gif)
please add `._scrollview` to your ref.
@SupriyaKalghatgi  needs to be documented.

**Comment by soukupl** [comment]
I just run to the issue when I needed to scroll the <Content> contents...

`this._content._scrollview.scrollToPosition(0, 0, false);` didn't work with error that _scrollview is undefined (but I can see it in the source code of <Content> component on git)...
`this._content._root.scrollToPosition(0, 0, false);` is working as expected...

**Comment by soukupl** [comment]
Hi @nobady90,
I don't remember why I did that, but since I moved my content loading logic to React's Context, I'm using this line of code to scroll back to top after content update...

`
setTimeout(() => {
   global.appContent._root.scrollToPosition(0, 0, false);
}, 50);
`

And in my main App.js, I have this REF set on the main content wrapper:

`
<Content ref={c => { global.appContent = c; }}>
   ...
</Content>
`

So... `global.appContent` is REF (stored in global space) to main wrapper and I'm asking the <Content>component to scroll to 0,0 (without animation - false).

The <Content> is from native-base :)

**Comment by rkrules** [comment]
@soukupl  That worked like charm ! Thanks so much. That's the simplest solution that worked and I tried quite a few things.
