### ISSUE TITLE
Scroll position not at top when going to new screen

### ISSUE THREAD

**Issue by perwagner** [GeekyAnts/NativeBase#1133]
Using expo.io, native-base and react-router v4, if my first page is a list, and I scroll down and click an element more than one screen size down on the list which links to a new page (a details page), the details page opens up also scrolled down (eg. it doesn't open at the top of the details page).

## Versions
expo.io: 19.0.0
react: 16.0.0-alpha.12
react-native: https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz
react-router-native: 4.1.1
native-base: 2.3.1
## Expected behavior
New page opens scrolled to the top, no matter what the scroll position was on the previous page.
## Actual behavior
New page opens scrolled down if user is scrolled down on the previous page.
## Example 
here: https://github.com/perwagner/react-native-expo-reactrouter4-nativebase-boilerplate
## Is the bug present in both ios and android or in any one of them?
Only tried on Android

**Comment by shivrajkumar** [comment]
@perwagner The way you have defined the routes is wrong. Routes are supposed to have the components, not the other way around. Please go through the docs for react-native-router.
Since you have the routes inside the components, even if you change the route/page, the outer component is still the same. Thus causing the scroll issue
