### ISSUE TITLE
Pull to Refresh does not work when FlatList nested inside <Content>

### ISSUE THREAD

**Issue by avin3sh** [GeekyAnts/NativeBase#1667]
I am on react-native `0.53.3` and native-base `2.3.9`.

I am using `FlatList` from `react-native` because some of the features which are not readily available in native-base's List component. And there is this one issue I am not able to solve.

The` FlatList` api of react-native provides native pull to refresh ability. While it works perfectly when FlatList is embedded inside `<View>`, it doesn't work if I nest it inside `<Content>`, pulling would simply do nothing.

I suspect this has something to do with margin and other styling elements because if you simply nest `FlatList` inside `<Content>`, the top and bottom margin won't fit perfect and you will have to use padding/margin styling to make the `FlatList` not go out of the view port.

**Comment by akhil-geekyants** [comment]
@avin3sh NativeBase `<Content/>` component is an implementation of `<ScrollView>`. You can use any method with `<Content/>` that makes pull to refresh work inside a `<ScrollView/>`.

**Comment by akhil-geekyants** [comment]
Closing this due to no response.

**Comment by immortalx** [comment]
I have the same issue. 
It doesn't work inside <Content /> or <ScrollView />. Maybe its a react-native issue?

**Comment by kstolte** [comment]
I also ran into this. Resolved it on my side by making the 

```
import { StyleSheet, RefreshControl } from 'react-native';

...
render(
  <Content refreshControl={<RefreshControl refreshing={this.state.refreshing} onRefresh={this._onRefresh.bind(this)} />}>
       <List .../>
      </Content>
...
)
```

**Comment by SupriyaKalghatgi** [comment]
Check with NativeBase 2.4.3
Also check release notes for this

**Comment by Yandamuri** [comment]
@kstolte Pull to refresh is working fine when I followed your solution. But the problem is unable to scroll the content down because, When I scroll down always pull to refresh is being called.How can I prevent this?

**Comment by cyblanceAndroidProject** [comment]
### ### ### ### ### ### ### ### ### ### ###

**Comment by davidfarinha** [comment]
I had a <FlatList nested inside <Content and I needed the pull-to-refresh working for my nested list- but the onRefresh wasn't getting called for me on this nested list, but was on the page level <Content refresher. I assumed this was due to the nested <ScrollView (one in <Content, another in <FlatList).
Problem with @kstolte  solution for me was I needed to render <RefreshControl in a nested way (not at <Content level at the top of the page) as my list wasn't fullscreen.
I fixed this by disabled scrolling at the <Content level and now my nested list's <RefreshControl onRefresh function is getting called and the pull-to-refresh is now working again.
```
 <Content scrollEnabled={false} contentContainerStyle={{ flexGrow: 1 }} >
```

**Comment by jhoanborges** [comment]
i had the same problem and i fixed it wrapping it into a Container instead of Content (i'm using Native Base).

**Comment by Aabir1** [comment]
I have the same problem and I fixed it By 
<Content padder contentContainerStyle={{ flex: 1 }}>

**Comment by bscaspar** [comment]
Hey @akhil-geekyants putting the onRefresh and refreshing props in `<Content>` doesn't work for me since my FlatList is on screen with other non-list elements, all nested in `<Content>`. The refresh control needs to show on the FlatList only, not on the whole screen. Is this an accepted use case for `<Content>`? If not, what would you recommend as a different structure?

**Comment by ikeliec** [comment]
> 
> 
> I am on react-native `0.53.3` and native-base `2.3.9`.
> 
> I am using `FlatList` from `react-native` because some of the features which are not readily available in native-base's List component. And there is this one issue I am not able to solve.
> 
> The` FlatList` api of react-native provides native pull to refresh ability. While it works perfectly when FlatList is embedded inside `<View>`, it doesn't work if I nest it inside `<Content>`, pulling would simply do nothing.
> 
> I suspect this has something to do with margin and other styling elements because if you simply nest `FlatList` inside `<Content>`, the top and bottom margin won't fit perfect and you will have to use padding/margin styling to make the `FlatList` not go out of the view port.

Removing it from Content will make it work.
