### ISSUE TITLE
Is it possible to optionally disable Picker button based on a condition?

### ISSUE THREAD

**Issue by VanessaChu** [GeekyAnts/NativeBase#1825]
How can I modify the Native Base Picker code to disable the button based on conditions?

**Comment by SupriyaKalghatgi** [comment]
@VanessaChu You can try that yourself
NativeBase Picker is implementation of React Native Picker

**Comment by ekimlinger** [comment]
This issue should not have been closed since this does not work on iOS.

@VanessaChu According to the RN docs, you can disable the input for their picker by passing an `enabled` flag, which works just fine on android. 

This however does not work on iOS and there is not currently a way to disable it.

**Comment by SupriyaKalghatgi** [comment]
@ekimlinger Your statement sounds invalid

As said earlier
> NativeBase Picker is implementation of React Native Picker

![image](https://user-images.githubusercontent.com/13464885/40100888-3744ffca-5903-11e8-9842-f8a072dd7b99.png)

Since React Native supports this only for Android, we cannot help in adding this to iOS

**Comment by SupriyaKalghatgi** [comment]
Released with [2.5.0](https://github.com/GeekyAnts/NativeBase/tree/v2.5.0)
