### ISSUE TITLE
react-native-vector icons && deprecated compile

### ISSUE THREAD

**Issue by Preeternal** [GeekyAnts/NativeBase#2290]
Could you please to update react-native vector icons?
https://github.com/oblador/react-native-vector-icons/issues/633

**Comment by g4laura** [comment]
possibly related to this... since upgrading to Xcode 10 I've had a build issue with my project:

error: Multiple commands produce '{path_to_project}/ios/build/Build/Products/Debug-iphonesimulator/{project_name}.app/Entypo.ttf':
1) Target '{project_name}' (project '{project_name}') has copy command from '{path_to_project}/node_modules/native-base/Fonts/Entypo.ttf' to '{path_to_project}/ios/build/Build/Products/Debug-iphonesimulator/{project_name}.app/Entypo.ttf'
2) Target '{project_name}' (project '{project_name}') has copy command from '{path_to_project}/node_modules/react-native-vector-icons/Fonts/Entypo.ttf' to '{path_to_project}/ios/build/Build/Products/Debug-iphonesimulator/{project_name}.app/Entypo.ttf'

**Comment by mnlbox** [comment]
@SupriyaKalghatgi an plan for this?
I have some issue with new gradle version.

**Comment by xchinjo** [comment]
same problem +1

**Comment by SupriyaKalghatgi** [comment]
Fixed with commit https://github.com/GeekyAnts/NativeBase/commit/f841390a7b4c9c88f9c8000689599783d5cfcf09 and https://github.com/GeekyAnts/NativeBase/commit/e678edbf19765421af50a1cdfc8ecd923976656b

Also available on `master`

**Comment by Preeternal** [comment]
![default](https://user-images.githubusercontent.com/24249735/47374065-c24da480-d6f5-11e8-8d44-0b65a3123d66.png)

**Comment by Preeternal** [comment]
No. It was from npm. Are latest master changes  present in npm?
