### ISSUE TITLE
ListView is deprecated and will be removed in a future release.

### ISSUE THREAD

**Issue by agersoncgps** [GeekyAnts/NativeBase#2398]
It looks like the Native Base List component uses a React Native ListView which is now causing depreciation warnings. 

https://facebook.github.io/react-native/blog/2017/03/13/better-list-views.html

**Comment by SupriyaKalghatgi** [comment]
NativeBase List was deprecated long time ago

![image](https://user-images.githubusercontent.com/13464885/47703511-857a3400-dc46-11e8-894f-038d66e0a1c9.png)

**Comment by SupriyaKalghatgi** [comment]
This is documented too

**Comment by agerson** [comment]
It does not appear to be documented here:

<img width="1150" alt="screenshot 2018-10-30 13 29 45" src="https://user-images.githubusercontent.com/334672/47737721-e5bda580-dc47-11e8-8d25-2c39512c265c.png">

**Comment by fitz0019** [comment]
I couldn't tell if I show open a new issue or re-open this.

This issue is not only to do with the NativeBase List it's also caused by <Content> which uses [KeyboardAwareScrollView Issue #316](https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/316). I think as soon as the fix has been applied NativeBase can update the dependancy to resolve it. This is more an FYI there is a problem and it should be fixable soon.

**Comment by ahce** [comment]
@SupriyaKalghatgi is necessary reopen this issue.
ListView has been removed in [v0.8.0](https://github.com/APSL/react-native-keyboard-aware-scroll-view/releases)
Is time to upgrade?

**Comment by SupriyaKalghatgi** [comment]
Released 2.10.0

**Comment by dsandor** [comment]
This is still an issue.  All of the documentation refers users to `List` as previously referenced by @agerson.

References to `List`:
- https://docs.nativebase.io/Components.html#dynamic-list-headref
- https://docs.nativebase.io/Components.html#list-def-headref
- https://docs.nativebase.io/Components.html#swipeable-multi-def-headref

Using v2.10.0 still produces `ListView is deprecated and will be removed in a future release.`

**Comment by dsandor** [comment]
It still seems like this is an issue and has not been addressed.  As long as we are using ListView here this warning will persist:

https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/List.js#L2

Just curious what the roadmap is to deprecate ListView.  I am afraid to use NativeBase on my projects because this could lock me down to the current version of RN.

**Comment by naytun** [comment]
Mu solution to <ListView> becoming obsolete is to use <FlatList> as follow:
```
const routes = [
  { key: "Account" },
  { key: "Settings" }
];
<FlatList
  data={routes}
  renderItem={({ item }) => {
    return (
      <ListItem onPress={()=>{}}>
        <Left />
        <Body>
          <Text>{item.key}</Text>
        </Body>
      </ListItem>
/>
```

**Comment by ssavva05** [comment]
The post above seems that get rid of the message! Thank you!

**Comment by MichaelVoelkel** [comment]
The "getting started" example on nativebase.io still uses ListView and that's v2.13. Many examples seem to be outdated, so how is this issue closed? (at least it should be linked here because Google leads here)
