### ISSUE TITLE
[Improvment] DatePicker IOs

### ISSUE THREAD

**Issue by ImBeCiliC** [GeekyAnts/NativeBase#2409]
The normal behaviour of the Date-Picker in IOs (Contacts, Calendar) is that the defaultDate is set as initialDate on open.
The attached code is a not tested or verified. Just my thoughts on a small UX improvment for the future.

```
<Modal
   animationType={this.props.animationType}
   transparent={this.props.modalTransparent} //from api
   visible={this.state.modalVisible}
   onShow={() => { this.setState({ chosenDate: this.state.defaultDate })}}
   onRequestClose={() => {}}
>
```

**Comment by SupriyaKalghatgi** [comment]
DatePicker has `defaultDate` field that can be set to date of user's choice OR current date

**Comment by halilcakarr** [comment]
Hello, 
I also have this on android. chosenDate property is setted but when i open it it's giving me like the date is 1 day previous.

![image](https://user-images.githubusercontent.com/18047554/47755109-2b14be00-dcae-11e8-89a7-145e4729331f.png)

This is the chosenDate which is today. And when i open the datepicker its shown like this: 

![image](https://user-images.githubusercontent.com/18047554/47755118-37991680-dcae-11e8-8675-3f4e755a823b.png)


And if i select this date which "Tue, Oct 30", when i open datepicker again its shows "Oct 29". 

Is this expected behaviour or is there something wrong on DatePicker or my code which is below:

```javascript
<DatePicker
    defaultDate={this.props.chosenDate}
    maximumDate={(new Date().setDate(new Date().getDate() + 1))}
    locale={'tr'}
    timeZoneOffsetInMinutes={undefined}
    modalTransparent={true}
    animationType={'fade'}
    androidMode={'default'}
    textStyle={styles.datePickerTextStyle}
    onDateChange={this.props.setDate}
 />
```

I also tryed to add chosenDate prop to DatePicker, It didn't change any behaviour.

**Comment by SupriyaKalghatgi** [comment]
I tried the snippet from NativeBase KitchenSink
```
          <DatePicker
            defaultDate={this.state.chosenDate}
            minimumDate={new Date(2018, 1, 1)}
            maximumDate={new Date(2018, 12, 31)}
            locale={"en"}
            timeZoneOffsetInMinutes={undefined}
            modalTransparent={false}
            animationType={"fade"}
            androidMode={"default"}
            textStyle={{ color: "green" }}
            placeHolderTextStyle={{ color: "#d3d3d3" }}
            onDateChange={this.setDate}
          />
```
`chosenDate` is `new Date()`

It works perfectly fine

**Comment by dacastro4** [comment]
@SupriyaKalghatgi it doesn't work if you change it after. Add this to `componentDidMount`
```
setTimeout(() => {
			this.setState({
				chosenDate: new Date(1991, 10, 4)
			})
		}, 5000)
```
Is not going to work
