### ISSUE TITLE
NativeBase not compatible with the latest version of react native 0.26

### ISSUE THREAD

**Issue by mrphu3074** [GeekyAnts/NativeBase#25]
Hi,
I just created  a new project and it's using rn ver 0.26. Then i got this error.

<img width="375" alt="screen shot 2016-05-20 at 14 45 02" src="https://cloud.githubusercontent.com/assets/1584592/15458552/c57ba8f2-20c5-11e6-8e86-ebcef1437940.png">

It's seems issue with ReactNativePropRegistry.

**Comment by Ginhing** [comment]
Same.
react-native 0.26 has some breaking changes which some modules were no longer inside.

**Comment by icukaegbu** [comment]
Looked through the code at development branch
<img width="796" alt="screen shot 2016-05-23 at 7 40 43 am" src="https://cloud.githubusercontent.com/assets/8110590/15462299/b79d20be-20b9-11e6-869d-41f315bd1a01.png">
The problem is that ReactNativePropRegistry from "react-native/Libraries/ReactNative/ReactNativePropRegistry" does not exist in RN 0.26 and above. 
Can this be resolved or replaced?

**Comment by sankhadeeproy007** [comment]
#26

**Comment by sankhadeeproy007** [comment]
RN 0.26 supported with latest update.
