### ISSUE TITLE
autoComplete property set to false on an Input element doesn't disable keyboard suggestions

### ISSUE THREAD

**Issue by leeuwerck** [GeekyAnts/NativeBase#2520]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node v8.11.3
npm 6.5.0
react 16.3.1
native-base 2.6.1

### Expected behaviour
When setting the property `autoComplete` to `false` on an `Input`, I would expect it to disable the Android keyboard suggestions.

### Actual behaviour
Android keyboard suggestions aren't disabled.

### Steps to reproduce

```
<Input
    autoComplete={false}
/>
```

### Is the bug present in both iOS and Android or in any one of them?
Tested on Android only.

### Any other additional info which would help us debug the issue quicker.
None.

**Comment by suvenduchhatoi** [comment]
@leeuwerck 
Actually the prop you should use is ```autoCorrect={false}```
![screen shot 1440-05-04 at 12 43 18 pm](https://user-images.githubusercontent.com/44160581/50952933-e4c2b300-14d7-11e9-97b8-eaa69ee46dd7.png)
But The issue seems to be already with ```<TextInput>``` of react-native which behaves the same way in Android. As  ```<Input>``` from NativeBase is built on top of it, it is also behaving the same way...
![screen shot 1440-05-04 at 12 56 14 pm](https://user-images.githubusercontent.com/44160581/50952963-f906b000-14d7-11e9-9b56-c8dfcbbfdd38.png)
But they are working as expected in Ios...
So, your issue is more of a react-native issue....

**Comment by anilrai01** [comment]
Have you found out any solution to this ? Cause I am still having such issues in Android

**Comment by felix-lambert** [comment]
Yes I would like to disable dashlane password manager. It seems to appear when I add the placeholder props on Input
