### ISSUE TITLE
How to disable drawer for particular scene?

### ISSUE THREAD

**Issue by mdmush** [GeekyAnts/NativeBase#255]
Hello GeekyAnts,

I just wanted to know how to disable drawer for a particular scene. Please tell me ASAP.

Thanks.

**Comment by sanketsahusoft** [comment]
@mdmush Since, Drawer's state and the Current Route are defined in the store (App's state) -- I think you will have to look into the reducer which changes the state of the drawer and modify it. You will have to check the current component in the Navigator state and not change the drawer's status for specific ones.
