### ISSUE TITLE
Documentation of buttons component does not match visual result (missing padding/margin)

### ISSUE THREAD

**Issue by allan-simon** [GeekyAnts/NativeBase#2583]
I'm following the example here https://docs.nativebase.io/Components.html#button-disabled-headref 
and the visual result i get does not match on two main points :

1. the overall padding is not present (I've fixed it by adding `padder` to `Content`
2. the buttons are stacked together without any margin (I've have figured yet how to fixed it)

your doc is overall pretty nice, but it would be even nicer if the copying the code would produce the same visual result as the screenshot next to the code :)  
I spent 30 minutes thinking something was wrong with my code/phone/expo version while finally finding 
http://discuss.nativebase.io/t/android-button-not-block/337

**Comment by suvenduchhatoi** [comment]
![screen shot 1440-06-14 at 12 33 44 am](https://user-images.githubusercontent.com/44160581/52971602-1768a100-33de-11e9-9a82-28550e8002ec.png)
The screenshot in docs has been taken from https://github.com/GeekyAnts/NativeBase-KitchenSink - The example app of NativeBase components. The code in docs has been intentionally kept short in order to avoid lengthy documentation

**Comment by allan-simon** [comment]
ok but my point stand, there's no disclaimer stating this, and as a normal user, if i see a piece of code and a screenshot next to it, it has to be the result of said code. So could you at least add a disclaimer ?
