### ISSUE TITLE
Help to support NativeBase with Gatsby RNW plugin

### ISSUE THREAD

**Issue by slorber** [GeekyAnts/NativeBase#2652]
Hi

I'm the author of the Gatsby RWN plugin and have tried to setup NativeBase for it, but without much success.

I've a demo here: https://github.com/slorber/gatsby-plugin-react-native-web/tree/master/examples/uikits

I've made an attempt here and commited the things that seemed to work: https://github.com/slorber/gatsby-plugin-react-native-web/commit/c0f0bbb1ecc82900bd5ee9af1e5b35a26167c2ad

The RN libraries seems to be transpiled properly, but I still get those errors:

![image](https://user-images.githubusercontent.com/749374/55292111-ea4cdc80-53e6-11e9-864b-b9d6532108a8.png)

![image](https://user-images.githubusercontent.com/749374/55292115-005a9d00-53e7-11e9-9b9f-5044b1601ad0.png)

This happens by just importing native-base and without even using it.

Could you help me try to fix my setup so that I can support NativeBase?

**Comment by SupriyaKalghatgi** [comment]
Please check the working repo here https://github.com/GeekyAnts/NativeBase-KitchenSink/tree/web-support

**Comment by esuus** [comment]
I'm disappointed you guys aren't supporting the Gatsby RN-Web effort more. Gatsby is the final upgrade that RN-Web needs in order to make it really attractive for production use. 
All other UI libraries work with it, just NativeBase doesn't. Please reconsider investing some time to support Sebastian in his effort @SupriyaKalghatgi .
