### ISSUE TITLE
Icon "active" not rendering filled FontAwesome5 icon

### ISSUE THREAD

**Issue by bohan0** [GeekyAnts/NativeBase#2660]
`<Icon name="comment-alt" active={true} type="FontAwesome5" />` should produce a filled icon, but it renders the unfilled one.

"native-base": "2.12.1"
"react-native-vector-icons": "6.4.2"

**Comment by SupriyaKalghatgi** [comment]
Not an issue
please go through docs
![image](https://user-images.githubusercontent.com/13464885/56035646-5cf37b80-5d48-11e9-89ff-9940442c3bd4.png)

**Comment by bohan0** [comment]
There is a filled version of comment-alt (fa version) where the whole icon is black.

Your screenshot shows unfilled icon which is nit the right behaviour.

**Comment by bohan0** [comment]
In vector-icons the option is called "solid"

**Comment by cristiankmb** [comment]
@SupriyaKalghatgi  There is not error, but the docs is not clear. <Icon active> Only work when we use the default type **Ionicons** but when i use another type like **FontAwesome5** active prop not work because **FontAwesome5** don't use _Outline_ o _Fill_ format like **Ionicons**.

@bohan0 You can play with icon color to show difference between yours icons.

```
<Icon name="comment-alt" color="black" type="FontAwesome5" />
<Icon name="comment-alt" color="gray" type="FontAwesome5" />
```
