### ISSUE TITLE
Bad Icons

### ISSUE THREAD

**Issue by Bizarrus** [GeekyAnts/NativeBase#2716]
```<Icon name="logo-ionic" />``` is bad, here the icon CC will be shown. Latest NPM Release!

**Comment by andidev** [comment]
`<Icon name="ios-list-box" />` is also bad, shows the cash icon instead

**Comment by andidev** [comment]
<Icon name="ios-notification-outline" />
<Icon name="md-business" />
 <Icon name="md-gift" />

is also wrong

**Comment by andidev** [comment]
Okey so I found out the issue here. Looks like somehow the latest version of vector icons was installed for me (6.5.0). Using 6.1.0 like the one included in the latest native base works. 

@Bizarrus 
I tried logo-ionic too. The correct icon is shown. Maybe you have the same issue as me. If so this issue should be closed.

**Comment by Juliocbr** [comment]
Hi @andidev,

Did you install the react-native-vector-icons v6.1.0 in your package.json or did you do other steps?

**Comment by Bizarrus** [comment]
For me, i had installed the latest version from NPM.

**Comment by hanykumar** [comment]
Hi @Bizarrus, you must install latest version of `react-native-vector-icons`.

Hi @andidev, please use `<Icon name="ios-notifications-outline" />` instead of `<Icon name="ios-notification-outline" />`. Other than these thing, all `<Icon {...props} />` works fine.

**Comment by hanykumar** [comment]
Hi @Bizarrus ,You must import Icon from 'native-base'.
latest version of Native base has been released. 

[Native Base 2.13.12](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.12)
