### ISSUE TITLE
[Android] this.props.children.toUpperCase() is not a function

### ISSUE THREAD

**Issue by ErkanSensei** [GeekyAnts/NativeBase#285]
Line 197 in Button.js:

```
return <Text style={this.getTextStyle()}>{(Platform.OS==='ios') ? this.props.children : this.props.children.toUpperCase()}</Text>
```

seems to cause a problem on Android.
Changing it to:

```
return <Text style={this.getTextStyle()}>{this.props.children}</Text>
```
fixes it.

**Comment by himanshu-satija** [comment]
[Line 197](https://github.com/GeekyAnts/NativeBase/blob/v0.5.13/Components/Widgets/Button.js#L197) should be unreachable if you have an Icon inside the Button or if you only have text. It is only reachable in case you have any other component with the text which will not be rendered anyway because Button only accepts Icon and raw text. We should remove that conditional from the code.

If you have any use case where it would cause a problem, let me know.

**Comment by ErkanSensei** [comment]
I only have text in my buttons, and this error only happens on Android, so I am not sure what is causing it exactly.

**Comment by SupriyaKalghatgi** [comment]
@ErkanSensei Got it working?

**Comment by ErkanSensei** [comment]
I fixed it and made a PR. It's working now!
