### ISSUE TITLE
Card animation

### ISSUE THREAD

**Issue by robtweed** [GeekyAnts/NativeBase#34]
Question regarding the new Card component.  Is the idea of these that you can slide between a set of cards using swipe gestures?  If so, could you indicate how this would be done?

Also are you planning on adding a navigator component, or should the standard React Native one be used?

Keep up the great work!

**Comment by sanketsahusoft** [comment]
@robtweed Thanks for the suggestion. Swipe cards component is not on the list at the moment. But we will consider that.

About Navigator, we are going to provide a free starter kit which will have some suggestions. Navigator is also not going to be a part of NativeBase anytime soon.

**Comment by maotora** [comment]
I thought i should just reopen this instead of making a new issue...

I'm using `<CardItem />` and it's rendering some cards which later can be removed.

After implementing this, I had a great urge to animate mounting and unmounting of a `<CardItem />`.

Can you consider this one too? Checked the source doesn't look like it's implemented but would really be cool to have some animations.

Thanks!
