### ISSUE TITLE
Question about what Dynamic List should be used for

### ISSUE THREAD

**Issue by booboothefool** [GeekyAnts/NativeBase#366]
http://nativebase.io/docs/v0.5.7/components#dynamicList

> A center aspect designed for efficient representation of vertically scrolling lists of changing data.

Does this mean where list changes (e.g. number of items), or the actual data of an item in the list can change?

For example, 

do you mean basic search results:
[a][b][c] => search by 'c' => [c]

or do you mean where the item can actually change: 
[a][b][c] => item c can change => [a][b][d]

I am just building a basic search/filtering with lots of items, but the items themselves do not change, and I do not know whether to use regular List or dynamic List. 

Thanks.

**Comment by himanshu-satija** [comment]
It only rerenders when the reference of the item changes i.e. when c !== d. But if you are changing something inside item c and the reference remains same (if it is the same object with updated properties), it won't rerender.

I know this is not ideal which is why we are going to change this behaviour in later versions but it will be a breaking change and the use case will become similar to React Native ListView.

If you don't have a lot of items, you can go ahead with regular List. Although for performance reasons, I would suggest using React Native ListView and rendering your items inside that with NativeBase ListItem.

**Comment by sanketsahusoft** [comment]
This exactly works like React Native's ListView. So, nothing specific to NativeBase.

We do have `dataArray` which is a handy prop which internally creates `dataSource`. Use `dataSource` and the functions of React Native's ListView for reference.
