### ISSUE TITLE
Stack `space` prop doesn't accept custom space theme key's

### ISSUE THREAD

**Issue by cmaycumber** [GeekyAnts/NativeBase#3882]
Usage: 

`theme.ts`
```js
space: {
 ...
'2xl': '96px',
}

```

`Component.ts`
```jsx
<Stack space='2xl'>
...
</Stack>
```

Using the stack component with `2xl` results in `32px` applied not `96px`

**Comment by rayan1810** [comment]
Hey @cmaycumber , once the fix is released you can extend Stack component theme and update your custom token. You can find the theme file here https://github.com/GeekyAnts/NativeBase/blob/fix/stack-space-not-extending/src/theme/components/stack.ts

**Comment by rayan1810** [comment]
@kylegwalsh @cmaycumber since Stack's space prop extends space tokens and adds additional values on component theme level therefore component theme overrides the base theme since it's higher on the precedence scale. If you want to override Stack's space with space token just do this
```
import { theme, extendTheme } from 'native-base';

const AppTheme = extendTheme({
    components: {
      Stack:{
        sizes:{ ...theme.space }
      }
    },
  });
}

```

We might take a look into other possibilities in future releases but currently, this is the way you can achieve the desired results. If this answers your question you can close this issue.

**Comment by kylegwalsh** [comment]
@rayan1810 Got it, that makes sense.

It was a bit unintuitive when we were setting it up, but it makes sense that it would get overridden by additional sizes declared at the component level.

Thanks for the tip!

**Comment by rayan1810** [comment]
Glad you agree. Closing this issue since I feel it is resolved. Feel free to reopen.
