### ISSUE TITLE
Disable scrolling in Modal body

### ISSUE THREAD

**Issue by dillondrobena** [GeekyAnts/NativeBase#3984]
Haven't found an answer for this anywhere so I thought I'd ask the question here. The default modal body component seems to be a `ScrollView` or something similar, but doesn't seem to provide a `scrollEnabled` property. Is there a way to disable the scrollable behavior?

Simple code example
```
    <Modal isOpen={true}>
          <Modal.Content>
              <Modal.CloseButton/>
              <Modal.Header >Modal Title</Modal.Header>
              <Modal.Body >
                  Sit nulla est ex deserunt exercitation anim occaecat.
              </Modal.Body>
              <Modal.Footer >
                  <Button.Group variant="ghost" space={2}>
                      <Button>LEARN MORE</Button>
                      <Button>Accept</Button>
                  </Button.Group>
              </Modal.Footer>
          </Modal.Content>
      </Modal>
```

This is using NativeBase 3.1.0 with ReactNative 0.63.3 on iOS

**Comment by rayan1810** [comment]
Thanks for Reporting this @dillondrobena, it will be fixed in the next Patch release.

**Comment by amosbastian** [comment]
@rayan1810 it's not fixed yet.

**Comment by rayan1810** [comment]
Once this PR https://github.com/GeekyAnts/NativeBase/pull/4215 gets merged and released, you can pass _scrollview to Modal.Body and it takes ScrollView props so you have full control over the underlying ScrollView. 
eg - <Modal.Body _scrollview={{ scrollEnable: false }}>

**Comment by yamatsum** [comment]
Correctly is `scrollEnabled: false`

**Comment by rayan1810** [comment]
My bad typo 🙈, thanks for correcting it @yamatsum

**Comment by surajahmed** [comment]
This issue has been fixed in version `3.2.2` or later.

**Comment by scipilot** [comment]
Is it possible to effectively remove the ScrollView? 

When there's a virtualised list in the modal body content I get this error: `"VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead. "` (as the virtualised list does its own scrolling while managing the list item construction and destruction off screen). 

I previously have solved this by removing the enclosing ScrollView - but in this case setting `scrollEnabled: false` doesn't resolve the error, even though it does affect the scroll behaviour.

**Comment by saurabhghadi0401** [comment]
Yes, the issue is still there with Modal Body.

**Comment by erclem1998** [comment]
Does anyone know if the problem will be fixed?

**Comment by amanape** [comment]
Removing the inner `<Modal.Body>` works as a temporary solution.

**Comment by JavaScriptJohn** [comment]
Still causing me issues.

**Comment by Christopher-Marim** [comment]
Change ```<Modal.Body>``` for ```<VStack p={4}```

**Comment by sangayt1997** [comment]
It's still in `"native-base": "^3.4.28"` but `_scrollview={{scrollEnabled: false}}` work well
