### ISSUE TITLE
Why are available components being removed from Documentation?

### ISSUE THREAD

**Issue by y471n** [GeekyAnts/NativeBase#4257]
**Describe the bug**
A number of components were present in earlier versions of the documentation, but most of the components although present in the source of the library, are not present in the documentation.

**To Reproduce**
See previous version documentation:
![Screenshot 2021-10-31 at 4 27 44 PM](https://user-images.githubusercontent.com/2056046/139579624-c85b4d24-d79e-4f51-9418-a74c7e3786de.png)

The newer documentation does not have those. Please see the screenshot. 
![Screenshot 2021-10-31 at 4 30 58 PM](https://user-images.githubusercontent.com/2056046/139579703-39244ba0-eb73-4b9a-9970-f825dc5a1eed.png)

Is this still an Open source project, or are the components being built by the community getting pushed to the paid version of the NativeBase?

**Comment by megacherry** [comment]
Good question. I also asked this on the discord channel (especially about Tabs) and the answer was that some components not (anymore?) production ready and has to be reworked.

**Comment by sanketsahu** [comment]
@y471n @megacherry This is a 100% open source project and it will always be. The components were moved away from docs because they were incomplete and we thought it wouldn't be nice for people to use the half-baked ones. We will bring them back.

Also, the paid version uses only these components as screens. So there are no new components in the paid version.

**Comment by y471n** [comment]
But I couldn't find any issues related to those components. Is there some other place where the issues are recorded then?

**Comment by rayan1810** [comment]
@y471n there are a few issues with the internal `architecture` of these components, during the initial phases of development we had experimented with a lot of different architectures to make the whole NativeBase design system(Theme and customizations) and component library work. So for the `alpha` and `beta` versions, we had these components on our Docs but we removed it since we found room for major improvements and the team wasn't happy with what we had. Also supporting a ton of components from day one is not a viable option for the team, we want to steadily grow NativeBase and listen to the community's existing problems first.

I request you to please hold on as we are actively working on updating these components, you might find some of them getting released in upcoming releases. I hope this answers your query. I'm closing this issue please feel free to reopen if you have any follow-up questions.✌️

**Comment by y471n** [comment]
@rayan1810 Could you please open this till it's being resolved. Otherwise, this just seems fishy to all the contributors or users of this library. 
And, This is not just a couple of components. This is also happening with a number of components. I would say with casual browsing it has at least 10+ components. The components are not deprecated but documentation is being removed selectively. 

If you plan to say this with regard to a change in the ideology of core-team at NativeBase/GeekyAnts, the thing to follow up would be to deprecate the components in upcoming releases or put in the documentation as it is in Alpha (and still not viable to be used in production). Isn't that a better option?

Please see from around 14 components down to 8 and this is just form inputs.

![Screenshot 2021-11-09 at 2 59 22 PM](https://user-images.githubusercontent.com/2056046/140898739-d94a9ba2-6339-488e-b2be-c8d186501216.png)

![Screenshot 2021-11-09 at 2 58 23 PM](https://user-images.githubusercontent.com/2056046/140898719-e2351c2c-8ad4-4251-87ab-bd409ed83c9a.png)

**Comment by rayan1810** [comment]
@y471n thanks for pointing out the concern. The docs that you’re referring to .next.* refers to the alpha versions. We apologies since it’s not very much clear from the naming convention we were following. But essentially these were alpha versions. We have a plan to release all the components, the only thing is that they lack quality and proper testing, even APIs might change. These are still present in the source so those who were using them in the alpha/next version can still keep on using them. i.e. they’re not deprecated, It’s just not officially released.

I think we can take your suggestion to put them in docs and label them as alpha. I’ll discuss it with the team and get back. Thanks for the suggestion!
