### ISSUE TITLE
Button fontSizes changed from v3.1 to v3.2 

### ISSUE THREAD

**Issue by floustao** [GeekyAnts/NativeBase#4259]
**Describe the bug**
Any reasons why the button fontSizes changed from native-base v3.1 to native-base v3.2?

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [sandbox](https://codesandbox.io/s/vibrant-easley-rn-v3-1-tw56o?file=/src/components/Example.tsx)
2. Inspect the button size `sm` -> 14px
3. Bump the dependency native-base to latest (3.2.1) or open this other [sandbox](https://codesandbox.io/s/vibrant-easley-rn-v3-2-vz6fg?file=/src/components/Example.tsx)
4. Inspect the button size `sm` -> 12px

![Screen Shot 2021-11-01 at 4 41 10 PM](https://user-images.githubusercontent.com/25415107/139756548-82e0e6b0-a7be-4952-9d43-f2da80e52303.png)
![Screen Shot 2021-11-01 at 4 35 57 PM](https://user-images.githubusercontent.com/25415107/139756550-daea381c-c0d3-4c4b-8646-077cad21e5c2.png)

**Expected behaviour**
Buttons are essential elements, I did not expect the library to update the fontSize from a version to another.
Wondering if that's expected as it breaks the consistency of our app.
Any easy workarounds?

Thank you!

**Comment by makkarMeenu** [comment]
Hi @floustao , UI was oversized because standard font sizes on react native mobile and web which is set to 14px, so we decided to reduce 1 size to make things look good by default.
[Here's](https://docs.nativebase.io/migration/migration-guide-three-point-two)  migration guide which mentions the workaround if you still want to use older theme.
