### ISSUE TITLE
Nextjs 12 support for Native Base

### ISSUE THREAD

**Issue by kmalakoff** [GeekyAnts/NativeBase#4295]
I've been using the generator for Next.js from these instructions: https://github.com/GeekyAnts/NativeBase/issues/2709

Build times are very slow and with Next.js 12 supporting swc, I'm hoping swc can speed up my development experience with react-native-web, Native Base, and Next.js. 

I posted the generated babel config from your Next.js boilerplate in their github issue collecting babel configs: https://github.com/vercel/next.js/discussions/30174

**Comment by exneval** [comment]
I want to thank @Ajamuar for updating the next.js template (support v12)

I just want to ask why people that want to start RN x Nativebase x Next.JS forced to used expo in the first place? because before the updates, we still able to use pure RN. Even Next.JS examples itself don't force such thing.

I think if someone want to use expo, there're already [a template exists for it](expo init my-app --template expo-template-native-base-typescript), or we want to support :
- expo x cra x nativebase (js / ts)
- expo x next x nativebase (js / ts)
- cra x nativebase, and (js / ts)
- next x nativebase (js / ts)

Thank you once again

**Comment by Viraj-10** [comment]
Thanks for reporting. All the mentioned combinations work with NativeBase now. If you are still facing some issues please feel free to reopen the issue.
