### ISSUE TITLE
When I set Input background color to "white" i get this warning: NativeBase: The contrast ratio of 1:1 for darkText on transparent

### ISSUE THREAD

**Issue by AshwiniKumar007** [GeekyAnts/NativeBase#4345]

**Comment by MD-REHMAN** [comment]
The warning states that the contrast ratio between the text colors and the background color is very less, meaning the text will be harder to read.

But if you want to suppress the warning you can use `suppressColorAccessibilityWarning`. You can simply pass it NativeBaseProvider's config prop.

```
<NativeBaseProvider 
  config={{
    suppressColorAccessibilityWarning: true
  }}
>
// Your Code.......
</NativeBaseProvider>
```

**Comment by thedewpoint** [comment]
Can I add that this warning is terrible and googling it reveals no information. I had to come here and search through the issues to find this fix. I also tried searching nativebase docs but didn't find this

**Comment by s0rta** [comment]
This isn't a real solution to the bug. I am getting the same response for black text on a white background in an input. What's really funny is that if the background is not set (transparent) the warning does not fire. I suggest removing 'transparent' from your wcag check, because that doesn't make any sense and is probably leading to problems elsewhere.
