### ISSUE TITLE
<Image> show warn:"Please pass alt prop to Image component" on React Native

### ISSUE THREAD

**Issue by laogui** [GeekyAnts/NativeBase#4389]
**Describe the bug**
<Image> show warn:"Please pass alt prop to Image component" on React Native，'alt' only use for web.

**Screenshots**
![image](https://user-images.githubusercontent.com/3276113/145320169-c698b8e5-3f2b-4f58-8f6b-3812270a2ef6.png)

**Platform**

- NativeBase version [3.2.2]
- Device: [OPPO find]
- OS: [android 11]
- React Native version [0.65]
- node [14.16.1]
- yarn or npm [6.4]

**Comment by rayan1810** [comment]
Alt is also required in React Native as accessibilityLabel that is read by screen readers therefore it's showing you a warning. Please provide an alt to image components so that if any person who is not as privileged as you and me are, is trying to use your app he/she can understand the content of all the images.

**Comment by Viraj-10** [comment]
Hi @laogui, Solution is provided for the issue.
