### ISSUE TITLE
Scrolling is not blocked on the elements behind the ActionSheet.

### ISSUE THREAD

**Issue by loveholly** [GeekyAnts/NativeBase#4417]
**Describe the bug**

**Expected behaviour**
Scrolling is  blocked on the elements behind the ActionSheet.

**CodeSandBox/Snack link**
https://codesandbox.io/s/crimson-glade-q4kk1?file=/src/App.tsx

**Comment by surajahmed** [comment]
@loveholly Thanks for reporting! We're looking into this.

**Comment by mayank-96** [comment]
@loveholly looks like it's been fixed in the current version, please check it once again and close the issue if it's working.

**Comment by nathanwkwong** [comment]
my codeSandbox example used native-base 3.3.5 with react-native-web 0.17.5 on web. The scrolling does disabled after the activesheet pop out. However, the its position is at the absolute bottom of the page, instead of poping out at the current position of the page. I need to scroll down to the lowset to see the activesheet. Is there any way to fix it?

https://codesandbox.io/s/busy-flower-5rpuj?file=/package.json

**Comment by nathanwkwong** [comment]
Instead of cloud sandbox, I tried to compile the same code and dependencies as https://codesandbox.io/s/busy-flower-5rpuj?file=/src/components/Example.tsx at my local develop environment. The whole page is still able to scroll after the activesheet pop out. Here is the problematic behaviour:

https://user-images.githubusercontent.com/55337066/153552493-cfca9725-a1e8-42da-b44c-2c7e5bc1986d.mov

I don't know whether it is the bug from native-base or other dependencies. Don't know someone have the same problem and got the solution. Thanks.

**Comment by nathanwkwong** [comment]
my codeSandbox example, https://codesandbox.io/s/busy-flower-5rpuj?file=/src/components/Example.tsx,  used native-base 3.3.5 with react-native-web 0.17.5 on web. The scrolling does disabled after the activesheet pop out. However, its position is at the absolute bottom of the page, instead of the current position of the page. I need to scroll down to the very bottom to see the activesheet. Is there any way to fix it?


video capture for the issue

https://user-images.githubusercontent.com/55337066/153555145-aa2b3a11-0558-45f4-a168-b51cf08c7976.mov

**Comment by nathanwkwong** [comment]
> my codeSandbox example, https://codesandbox.io/s/busy-flower-5rpuj?file=/src/components/Example.tsx, used native-base 3.3.5 with react-native-web 0.17.5 on web. The scrolling does disabled after the activesheet pop out. However, its position is at the absolute bottom of the page, instead of the current position of the page. I need to scroll down to the very bottom to see the activesheet. Is there any way to fix it?
> 
> video capture for the issue
> 
>  Screen.Recording.2022-02-11.at.3.48.11.PM.mov

Just found that it seems the above issue is the same as in here, https://github.com/GeekyAnts/NativeBase/issues/4581, affected on both native-base's modal and activesheet module.

**Comment by Viraj-10** [comment]
This issue has been fixed in `v3.4.8`.
