### ISSUE TITLE
theme baseStyle not working

### ISSUE THREAD

**Issue by kdong007** [GeekyAnts/NativeBase#5089]
### Description

theme baseStyle not working

### CodeSandbox/Snack link

https://snack.expo.dev/@kdong007/mad-watermelon

### Steps to reproduce

see the sandbox link

### NativeBase Version

3.3.1

### Platform

- [X] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by ankit-tailor** [comment]
Hi @kdong007 , please use the following code to change color.
```
Text: {
   baseStyle: {
    _light: {
        color: 'red.900',
       },
   },
}
```
We have used `_light` and `_dark` in baseStyle and it is getting combined with `extendedTheme`. `_light` and `_dark` has higher specificity than normal props that's why it's not getting applied. We will fix _light and _dark issues till then please use the following workaround. for now, it's mandatory to pass it inside a _light or _dark.

**Comment by kdong007** [comment]
Thanks for the answer. :D
