### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by vahidreza** [GeekyAnts/NativeBase#518]
Hi
Im in the phase of starting to learn react native and also use nativebase as its template. 
My main question here is the support of RTL layouts for multi culture apps.
Does nativeBase support RTL and is there any guide regarding this matter?

**Comment by sanketsahusoft** [comment]
We don't have RTL at the moment but that's on our roadmap.

**Comment by vahidreza** [comment]
Can you give me an approximate date for the feature to be shipped?

**Comment by sanketsahusoft** [comment]
Not any time soon. It will take at least 4 to 6 weeks. We have a lot of things on our list but we are trying our level best to push forward as soon as possible.

**Comment by vahidreza** [comment]
Tnx kumar for your prompt reply. Actually im intending to learn react
native and it takes at least 2 months. Im planning to recode one of my
products using react since then. So, I need the RTL feature for at least 3
months from now. I know giving an answer is not easy for this question but
i only need a probability.
Tnx

**Comment by BlackStarGr8** [comment]
https://checkout.stripe.com/v3/ZQdHTgQQb08RG01SxL4MA.html?distinct_id=da

**Comment by cyclops24** [comment]
@sanketsahusoft are you any news about RTL support?

**Comment by Aleksandern** [comment]
Hello.
Any chance about RTL support?
Thanks.

**Comment by RamyarIran** [comment]
Any chance to contribute ? Maybe the only way works for now...

**Comment by sankhadeeproy007** [comment]
Yes, we'll be happy to accept PR's for RTL support.

**Comment by MahdiMajidzadeh** [comment]
+1

**Comment by MohamedHedar** [comment]
any updates about the RTL support ?

**Comment by eyadfarra** [comment]
Any RTL updates ?

**Comment by roysG** [comment]
any update?

**Comment by mimalef70** [comment]
+1

**Comment by basir** [comment]
+1

**Comment by yoavapi** [comment]
what is not working in RTL?

**Comment by devaloreLtd** [comment]
+1

**Comment by eldadcaspi** [comment]
+1

**Comment by blackhair** [comment]
+1

**Comment by mrfarhadir** [comment]
+1

**Comment by n1arash** [comment]
+1

**Comment by MohamadKh75** [comment]
+1

**Comment by mahshadalishahi** [comment]
+1

**Comment by habibi-dev** [comment]
low priority :|

**Comment by sijav** [comment]
I'm putting some of the RTL issues with this UI Toolkit, for those who are interested

One of the issues I've been encounter was icons,
arrow-back is pointing forward in case of RTL, it can be easily fixed by setting another pack of NBIcons.json with every forward to back and vice versa, every right to left and vice versa, and then in src/icon/index put something like this:
```
...
import { Platform, I18nManager } from "react-native";
...
import icLTR from "./NBIcons.json";
import icRTL from "./NBIcons-rtl.json";
...
class Icon extends Component {
    ...
    getName() {
        ...
        const ic = I18nManager.isRTL ? icRTL : icLTR;
        ...
    }

    getIconName() {
        const ic = I18nManager.isRTL ? icRTL : icLTR;
        ...
    }
}
```
and that's it, now in case of rtl all icons will read their true icon names through `NBIcons-rtl.json` instead of `NBIcons.json` ... I'll create a PR for it later.

Another issue I've been encountered so far is with tabs, it seems that in normal and advanced tab cases both tab indicator and tab's text active highlight are wrong and instead of showing active for the first tab they're showing the last tab(wrong) ... why? I have no idea yet, in case of Scrollable tabs things are much funnier, the tab indicator is at it's right place and will show the first tab (correct) but the tab highlight is at the last tab (wrong) and the scroll goes to the last tab(wrong)!
the buttons are acting exactly vice versa clicking on the last tab will show the first page and clicking on the first tab will show the last page.
[Tab issue 1](https://cdn.pbrd.co/images/Hgv536v.png) [Tab issue 2](https://cdn.pbrd.co/images/Hgv5xsw.png) [Tab issue 3](https://cdn.pbrd.co/images/Hgv5IUT.png)

The other issue is the drawer at first it comes from the left to right but then it correct itself and animate it from right to left, however randomly it might encounter some issue in which the drawer button won't show the drawer ... you can open the drawer by swiping from right to left but it won't close itself when clicking a menu

Another issue which is the most funny of all is segments ... I'm putting some screenshots for you so you can understand it
[Segment issue 1](https://cdn.pbrd.co/images/Hgv6fqG.png) [Segment issue 2](https://cdn.pbrd.co/images/Hgv6i5S.png)

Another issue is picker, well maybe just a style issue? perhaps?
[Picker issue](https://cdn.pbrd.co/images/Hgv71WZ.png)

Radio button like the image are always off
[Radio issue](https://cdn.pbrd.co/images/Hgv7rdE.png)

Deck swiper have issues as well ... if you swipe the first card the third card will suddenly appear for a sec then it will disappear and second card will appear ...

Style issues in List Separator (probably padding or margin)
[List Separator issue](https://cdn.pbrd.co/images/Hgv7UHC.png)

Style issues in check boxes...
[CheckBox issue](https://cdn.pbrd.co/images/Hgv8mln.png)

Everything else seems to work just fine ...
Sorry for the long message

**Comment by hemeda3** [comment]
+1

**Comment by HosseinRashno** [comment]
any updates about the RTL support ?

**Comment by alihatam** [comment]
+1 for RTL support

**Comment by mAmged** [comment]
+1

**Comment by MahdiMajidzadeh** [comment]
+1

**Comment by mohsensaremi** [comment]
+1

**Comment by bemaxima** [comment]
+1

**Comment by mAmged** [comment]
@SupriyaKalghatgi you may need to change the priority now 💯

**Comment by AliRadmanesh** [comment]
I really need RTL support. please add this feature in the new update.

**Comment by omidd1315** [comment]
+1

**Comment by FadiAboMsalam** [comment]
+1

**Comment by ramyareye** [comment]
As I did in my project I included an rtl file beside my main style, playin with flex easily makes it RTL. 
I just don't know how to do it the best way and contribute

**Comment by Shtibel** [comment]
+1

**Comment by bepehr** [comment]
+1

**Comment by 7aduta** [comment]
1+

**Comment by FadiAboMsalam** [comment]
i am still facing the tab issue in RTL 
any workaround for it ?

**Comment by AliRadmanesh** [comment]
@FadiAboMsalam  As a workaround you can use [react-native-tab-view](https://github.com/react-native-community/react-native-tab-view).
Aslo it has some issue in reversing swipe, but it works and usable. (better than native base tabs)

**Comment by HinnHabib** [comment]
+1

**Comment by RatebSeirawan** [comment]
still no rtl support! 
I got hit in the face after developing an app when I changed the layout to rtl, thought it was mandatory to be supported in such library

**Comment by RatebSeirawan** [comment]
trying a fast fix, so far it's working good with no issues 
just override the container style like this
<Body style={{alignItems:'flex-start'}}>
when changing to rtl it will change flex-start to flex-end automaticlly

**Comment by iraniamir** [comment]
waiting for it !

**Comment by Tohid1999** [comment]
any update?

**Comment by ielhag** [comment]
+1

**Comment by mm7mod** [comment]
+100 xD ... is there a guide line that we can follow either to contribute to this project to add RTL support or even to add it locally to our APPs ... I need this feature

**Comment by nafiln** [comment]
+1 for RTL support Thanks in advance

**Comment by ehab666** [comment]
+1 for RTL support

**Comment by Fedorrychkov** [comment]
+1 for RTL support

**Comment by cybercoder** [comment]
I changed my TABs like this to work correctly:

```javascript
import { Platform, I18nManager } from 'react-native';
....
<Tabs>
data.map((node,index)=>{
     return (
          <Tab key={index} heading={......}>
               <MyComponent {...props} itemToShowId = {
                  I18nManager.isRTL
                    ? Platform.OS === 'android'
                      ? data[data.length - 1 - index].id
                      : node.id
                    : node.id
                }
          </Tab>
     )
}
</Tabs>
```
May it is useful for you.

**Comment by saivyas** [comment]
I had problem with native base tabs when I did forceRtl. Everything works but only native base doesn't show anything on initial load .

So I had a temporary solution

@ https://stackoverflow.com/questions/58736619/nativebase-tabs-issue-for-force-rtl-fix/58736621#58736621

**Comment by Lampent** [comment]
Still, no one did it? Can I make a PR with a fix for it?

**Comment by emnuu** [comment]
+1

**Comment by Mansour-J** [comment]
Getting to end of 2020 for an issue that was raised in early 2017!

P L E A S E - how long would it take to convert some of these to RTL ?  (You can specific donation for RTL, if it's a big deal)

BTW, I love the work that goes into this library <3

**Comment by hanykumar** [comment]
Hi @Lampent , we will be grateful if you create PR for the same.
Thanks

**Comment by muhammadhassan149** [comment]
> I changed my TABs like this to work correctly:
> 
> ```js
> import { Platform, I18nManager } from 'react-native';
> ....
> <Tabs>
> data.map((node,index)=>{
>      return (
>           <Tab key={index} heading={......}>
>                <MyComponent {...props} itemToShowId = {
>                   I18nManager.isRTL
>                     ? Platform.OS === 'android'
>                       ? data[data.length - 1 - index].id
>                       : node.id
>                     : node.id
>                 }
>           </Tab>
>      )
> }
> </Tabs>
> ```
> 
> May it is useful for you.

Hello, can you please share the complete code of this example

**Comment by Saad9624** [comment]
any update on RTL?

**Comment by rezatoosi** [comment]
Tabs +1

**Comment by soly2014** [comment]
any update on RTL?

**Comment by awgrass** [comment]
Please add RTL support!

**Comment by ramyareye** [comment]
I switched to React Native Paper

**Comment by vitaly87** [comment]
Please add RTL support!

**Comment by maqeelqureshi** [comment]
+1

**Comment by KianooshSoleimani** [comment]
> We don't have RTL at the moment but that's on our roadmap.

I think your roadmap got broken because you said this on 2017 pal 😉😏😐

**Comment by y471n** [comment]
+💯

**Comment by alitnk** [comment]
+1 Would love it to have RTL support.

**Comment by navidkhalilian** [comment]
+1

**Comment by y471n** [comment]
For those still waiting for this to arrive.
I actually got this working with [i18n-next](https://react.i18next.com/). It works well. Just use:
```
textAlign = 'left'
```

in NativeBase's `Heading` and `Text` components, so that they automatically right-align themselves when in Right mode.

**Comment by MainAdc95** [comment]
hmmm...

**Comment by Ali-Aref** [comment]
Any updates ?! I guess we won't have RTL support. :(

**Comment by Lalmi-Issam** [comment]
I think RTL will never be implemented to this project you need all to find some walk around for this feature
