### ISSUE TITLE
Weird behavior/bug of DeckSwiper when swiping fast

### ISSUE THREAD

**Issue by juergengunz** [GeekyAnts/NativeBase#545]
I discovered an Issue/Bug or weird behavior when I try to swipe the cards fast.
See Video: https://www.youtube.com/watch?v=2EtvIg42Trc&feature=youtu.be

Is this bug known and are there any solutions already?

**Comment by sankhadeeproy007** [comment]
No we haven't come across such an issue yet. Did you try it out on a device or a simulator?

**Comment by n8stowell82** [comment]
I had a similar issue but when I swipe a card half way and release it can get stuck.  trying to swipe it back out of the way lead to it getting stuck in multiple different ways even bleeding off onto previous scene

**Comment by n8stowell82** [comment]
I have a fix for the "sticking" issue.  I am working on preparing a PR to fix.  Basically the pan responder is being occasionally terminated instead of succeeding.  The termination event was not being listened to and so the deck become erratic.  By adding the termination event watcher and performing the same logic as in the "release" listener, the deck will behave appropriately regardless of how fast/far you swipe

**Comment by SupriyaKalghatgi** [comment]
@n8stowell82 Any update on the PR?

**Comment by SupriyaKalghatgi** [comment]
[#826](https://github.com/GeekyAnts/NativeBase/issues/826)
