### ISSUE TITLE
Slow performance on Android

### ISSUE THREAD

**Issue by yustnip** [GeekyAnts/NativeBase#593]
I've noticed that on Android the usage of NativeBase makes an app slowly. On iOS all is OK. For example I've made a simple project from the scratch [here](https://github.com/yustnip/SampleApp/blob/master/index.android.js).

In the mentioned example if I press "Do smth" button, while the setInterval process is running, I get no result or get it with a delay.

If NativeBase components is replaced for standard React Native components like TouchableOpacity it works pretty fast.

On the gif below I'm trying to press "Do smth" button to execute a simple alert().

![itzmjf](https://cloud.githubusercontent.com/assets/9950871/23568895/db68f5ce-006d-11e7-843a-be0131fe1fd0.gif)

*react-native, react and native-base version*
0.42.0, 15.4.2, 2.0.12

**Comment by winnie2012** [comment]
+1

**Comment by brainbow91** [comment]
I also noticed this... on Android the performance is very bad.

**Comment by srhise** [comment]
I came to the sad conclusion of this as well. The button splash animations sometimes run so slow that the look to be in slow motion, even in a release build. The app layout is perfect, no issues and looks great across both platforms, but the performance is bad.

**Comment by sankhadeeproy007** [comment]
Yes, that is actually an issue right now. But we've already figured out a fix for this and testing it out on branch [caching](https://github.com/GeekyAnts/NativeBase/tree/caching). We're testing it out internally and would love it if you could test it and let us know as well.
cc @yustnip @brainbow91 @srhise

**Comment by srhise** [comment]
I can test the branch. I find the performance mostly an issue on <List> and <ListItem button />

I will test it right now. I apologize for possibly a stupid question, what is the best way to pull down this branch into my existing RN project? I have a local dev branch I can bring it into, but is there an npm version that I can grab?

**Comment by sankhadeeproy007** [comment]
Just update your package.json
```
"native-base": "https://github.com/GeekyAnts/NativeBase#caching"
```

**Comment by srhise** [comment]
Ok, here's what I notice with the updated library: 

- Performance seems a bit better as it seems some animations (button splash effect) have been removed
- I am getting an error on both iOS and Android. 

![image](https://cloud.githubusercontent.com/assets/914113/24165593/2eed3912-0e47-11e7-8383-0d988505498f.png)

I will note, that I was using 2.0.11 when I posted this response so I installed 2.0.13 as well. I noticed the same performance as the [caching](https://github.com/GeekyAnts/NativeBase#caching) branch, so I am not sure what gains are made there. 

Any ideas on that error?

**Comment by sankhadeeproy007** [comment]
It looks like it is trying to access the touchableHighlight component of RN. And that shouldn't be the case because on Android we render the TouchableNativeFeedback component. Hence the ripple animations are gone.
Also it's hard to understand why there would be any performance improvement in 2.0.13 because we've just added new components to it, rather than making any changes to the core.

**Comment by srhise** [comment]
That fixed it.. I am still having performance issues on Android with this version. What specifically was added to that branch that I should look out for in terms of improved performance?

**Comment by shivrajkumar** [comment]
Performance issue resolved in v2.1.0

**Comment by MSchmidt** [comment]
Are they? I'm still finding it quite slow in comparison to iOS. Maybe it was even worse before 2.1 but I just ran the Kitchen Sink for the first time an immediately realised that it doesn't feel "native" at all.

**Comment by KrajncJ** [comment]
I also noticed a similar problem. 
It is true that performance was poor in previous versions, but in v2.1.0 performance have improved a lot.
Since I updated my phone to Android 7.0 the performance is pretty bad again.

**Comment by srhise** [comment]
Is there hope for better performance on Android? I don't see any improvements in the latest versions. Is there a list of tips and tricks for Android performance with Nativebase?

**Comment by orangecoloured** [comment]
FAB component lags horribly. I thought maybe simply adding `useNativeDriver: true` could do the thing, but no success.

**Comment by michelalbers** [comment]
I spent a full day of hair pulling and implementing performance optimizations. I switched to https://github.com/react-native-training/react-native-elements and now the app runs super smooth.

**Comment by svlada** [comment]
@michelalbers What kind of performance issues you've encountered?

**Comment by douglasjunior** [comment]
My problem with NativeBase is with Apps startup. When I put NativeBase in my project, the App take 3x more time to start.

**Comment by Laurensdc** [comment]
When I'm using React Navigation, the Tabnavigator is extremely slow using NativeBase. There is a ~1s lag after pressing before the screen responds.
If I spam touch, the touches also seem to be buffered, so that the screens will just go nuts from left to right for a few seconds.

I have the same issue with TouchableOpacity, when I remove NativeBase, everything is super smooth, but in combination with NativeBase components, there's a ~1s lag before the touch gets processed.
The component goes to state 'pressed', then the screen lags for ~1 second, and then the touch gets pressed and the component goes to state 'unpressed'.

NativeBase looked extremely promising, but unfortunately I'm going to have defer from using it.

**Comment by SupriyaKalghatgi** [comment]
#1012

**Comment by AgNm** [comment]
@Laurensdc did you find any solution, I am using Nativebase throughout my app

**Comment by rochapablo** [comment]
It still slow =/

"native-base": "^2.8.0",

**Comment by mfaghfoory** [comment]
I've removed native base from my project and now, everything is normal

**Comment by Jshaider** [comment]
native base is too slow.. i wish if i had seen this before.. :(... now I need to do all that from the start.. 
can someone tell me what to use instead of ActionSheet

**Comment by mfaghfoory** [comment]
> native base is too slow.. i wish if i had seen this before.. :(... now I need to do all that from the start..
> can someone tell me what to use instead of ActionSheet

There are several options you can choose. take a look at this
https://github.com/beefe/react-native-actionsheet

**Comment by PA55ION** [comment]
It's still super slow

**Comment by annjawn** [comment]
Speed on Android is Terrible. I am facing the exact issues as @Laurensdc . Touches respond at a delay for almost ALL buttons and screen navigations are slow too. This is based on testing on a real device with no remote js debugging on, no console logs etc. Infact, my app isn't even connected to the backend APIs yet, but it's slow. I am worried that performance will drop drastically when the App will start making api calls.

**Comment by ansarikhurshid786** [comment]
Yes, I am also facing same issue in android. iOS performance is good

**Comment by michaelVictoriaDev** [comment]
Im using nativebase but still slow, I try to optimize my code, but still a problem in 2020 :(

**Comment by annjawn** [comment]
I think in Exop Production mode the speed seems somewhat acceptable in Android and it seems normal, but in Dev mode the speed is horrible.

**Comment by TheSalarKhan** [comment]
The action sheet takes ages to load if the list size is long

**Comment by korbonya** [comment]
Still having the same problem with action sheet too slow.

**Comment by KazakovVS** [comment]
Super slow on some android devices. By looking at the history of this thread doesn't look to be promising. Seems like the only way is to switch to another lightweight solution or just create all desired components from scratch...

**Comment by pierroo** [comment]
Unfortunately after 2 monts live, I have to say that I will have to switch back to native component as well.
Which leads me to rewrite an entire app nearly from scratch in terms of frontend, potentially a month wasted of development.
Tried the latest 3.3.4 native-base version with hope, but unfortunately performance on android just are terrible.

**Comment by gitalvininfo** [comment]
NativeBase looks promising really helps me in speeding the development but seeing others complaining about the performance issues and also experiencing it, switching to native components is the ideal solution. 

For me the issues I encounter are

1. Startup of app takes at least 3 seconds to initialize even the app itself is just too small. (3rd party package are @react-native-community/datetimepicker, @react-native-async-storage/async-storage, @react-navigation/native-stack, @react-navigation/material-top-tabs)

2. When I press the tabs there is always a delay of at least half a second for the app to respond on first initialization as what @Laurensdc has said.

3. Putting the checkbox inside touchable opacity is also slow to respond and at least 1 second in order for it to check the checkbox.

4. Even though I generated a release signed apk, this slow performance is still present, I thought this is only happening in development.


For anyone who thinks to use nativebase in their project, consider testing it for yourself first if you are convinced with its performance, otherwise just use the native components.

**Comment by gitalvininfo** [comment]
I noticed after I rewrite all my code and change nativebase element to just react native elements, there is really a significant difference between the two. The startup of app takes only less than a second and there's no delay in response of clicking. The only problem is I have to manually add the css styling.

I hope the release of v4 will fix some performance issues.

**Comment by pierroo** [comment]
We all have high expectations on v4.
It will be a turning point for me and probably many other developers who got stuck with native base in production after a bad decision.

If they finally fix the performance issue, I will remain loyal.
If they do not, I will finally take the leap of rewriting my entire code and get rid of it and never look back for all the time and energy I wasted optimizing every possible functions and screens with the hope to compensate the lacking of native base.

Best of luck devs at native base, we count on you! :)
