### ISSUE TITLE
header centralized

### ISSUE THREAD

**Issue by franciscocpg** [GeekyAnts/NativeBase#604]
Hello.
Why is header centralized on iOS but not on Android? 
Is there a way to centralize it on Android?

**iOS**
![iOS](http://nativebase.io/assets/img/Button%202.png)
**Android**
![Android](http://nativebase.io/assets/img/Button.png)

## react-native, react and native-base version
2.0.12

**Comment by sankhadeeproy007** [comment]
It is not centralized on android because, google material design guidelines say that the title should be aligned to the left.
If you want it centered, 
![screen shot 2017-03-07 at 1 37 14 pm](https://cloud.githubusercontent.com/assets/10998047/23647303/35250c90-033b-11e7-9213-a4e6fbdaa9ff.png)
making these changes to the header will fix it.

**Comment by franciscocpg** [comment]
thank you @sankhadeeproy007 
I was taking a look at inbox app for android and I noticed this guideline, Eg ("Inbox" title is aligned to the left)
![inbox](https://lh3.googleusercontent.com/NqdzyzoxqTBXVZrrZYpU4BG19-QhA8gdBhmf3nkfvVJ7d4VqANee_F3114HHdt2lAHw=h900)

**Comment by lilin666** [comment]
@franciscocpg  it works thank U
