### ISSUE TITLE
Can't use react-native-vector-icons inside <Left></Left> 

### ISSUE THREAD

**Issue by vexsnare** [GeekyAnts/NativeBase#606]
I only use native-base for some component do not entirely want to depend on this library. This time I  was trying to use **ListItem** but got stuck into this problem.

## react-native, react and native-base version
react-native: 0.40
react: 15.4.2
native-base: 2.0.0

## Expected behaviour
I should be able to use react-native-vector-icons. 

## Actual behaviour
Currently it only works with inbuilt Icon of native base.

## Steps to reproduce (code snippet or screenshot)
`import { FontAwesome } from 'react-native-vector-icons/FontAwesome';`

```
<ListItem>
          <Left>
            <FontAwesome name="user" size={22} />
          </Left>
          <Body>
            <Text>{contact_number}</Text>
          </Body>
</ListItem>
```

Above code doesn't work, but following code works

`import { Icon } from 'native-base';`

```
<ListItem>
          <Left>
            <Icon name="person" size={22} />
          </Left>
          <Body>
            <Text>{contact_number}</Text>
          </Body>
</ListItem>
```
## Is the bug present in both ios and android or in any one of them?
Yes

**Comment by amelzer** [comment]
Do the Icons work outside of native-base components?

**Comment by vexsnare** [comment]
Yes

**Comment by sankhadeeproy007** [comment]
Just curious to know, why are you not using the fontawesome icons bundled with nativebase?

**Comment by vexsnare** [comment]
1. I am used to using vector-icons directly which are pretty straight forward, you just have to import provide name, size and color that's it.

2. Didn't like the approach of native-base in this aspect. In case of icons too I have to provide size and color under style prop. Which is changing complete set of rules that you read in actual vector icons documentation. Writing wrapper around a library is a good practice but only if it is required.

3. Why am I being forced to use trivial **<Icon>** component when I just wanted to use **<ListItem>**. Each native-base component itself should be pretty _flexible_ & **adoptable**.

**Comment by ericvan76** [comment]
@vexsnare, There is no icon called "person" in [FontAwesome](http://fontawesome.io/icons/), and native-base's default icon family is [Ionicons](http://ionicframework.com/docs/v2/ionicons/), that's where "person" came from. You can change the icon family via [themes](http://nativebase.io/docs/v2.0.0/customize#themingNativeBaseApp) if you want to use any icons from FontAwesome.

**Comment by vexsnare** [comment]
@ericvan76  Is there a way I can import and use one from FontAwesome & another from Ionicons within a component, as I can do with react-native-vector-icons.

**Comment by ericvan76** [comment]
@vexsnare, like what I said, you can connect with different theme, or use 'react-native-vector-icons' directly. you did nothing wrong in your original post, it's not working just because that icon name "person" doesn't exist in FontAwesome. For more details, please look at [IconNB.js](https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/IconNB.js#L22-L53) and [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons).

**Comment by vexsnare** [comment]
@ericvan76 Yes it does. Thank you for providing right information. closing this issue!

**Comment by peterchibunna** [comment]
I don't know but I still am not able to do this.
This is my code below:
`<Icon name={"magnify"} theme={{iconFamily: "MaterialCommunityIcons"}} />`
But I get a '?' sign instead.

I've read the code; the documentation but I've not found a way out.

NB. I don't want to do `<MaterialCommunityIcons ... >` because the other style options  and properties are lost. (not displaying as should, either with a different size or color, especially if I'm using another icon in a tab, the tab icon color effects are lost)
