### ISSUE TITLE
Tab stops showing as active between 2.0.12 and 2.1.0

### ISSUE THREAD

**Issue by nagolyhprum** [GeekyAnts/NativeBase#705]
**react-native, react and native-base version**
rn: 0.42.3, r: 15.4.1, nb: 2.1.0

**Expected behaviour**
Active tab should display differently from other tabs

**Actual behaviour**
The first tab is always displayed as active (The underline moves but styling does not).

**Steps to reproduce (code snippet or screenshot)**

1. Use the Tabs sample http://docs.nativebase.io/COMPONENTS.html#Tabs.
2. Click the second tab.
3. First tab is still displaying as selected.

**Is the bug present in both ios and android or in any one of them?**
Only tested in Android

**Any other additional info which would help us debug the issue quicker.**
This code does work in an earlier version 2.1.0

**Comment by fbacker** [comment]
Same for mem on iOS

**Comment by yagiro** [comment]
Same for me on Android (7.1.1)

**Comment by ErkanSensei** [comment]
Same for me on iOS

**Comment by jsheng08** [comment]
I face the same problem and I fixed it with a temporary hack.

1) Eject the theme using.
`node node_modules/native-base/ejectTheme.js`

2) Import the variables found in the theme to the component.
`import variables from '../../native-base-theme/variables/platform';`

3) Add the textStyle and activeTextStyle to every Tab so that it updates accordingly.
```
<Tab  heading="Hello Tab"
           textStyle={{ color: variables.topTabBarTextColor }}
           activeTextStyle={{ color: variables.topTabBarActiveTextColor }} >
```

Hope this helps. It works for both Android and iOS.

**Comment by shivrajkumar** [comment]
Merge the theme of newer version with already ejected theme of previous version.
