### ISSUE TITLE
mutiline textinput has only one row

### ISSUE THREAD

**Issue by uriva** [GeekyAnts/NativeBase#745]
Using `multiline` works, but it still appears as 1 line (even when using `numberOfLines`)
```
<Item last>
  <Label>Say something</Label>
  <Input
    multiline={true}
    numberOfLines={4}
    onChangeText={text => {
      this.setState({ text });
    }}
    blurOnSubmit={true}
    returnKeyType="next"
  />
</Item>
```

**Comment by shivrajkumar** [comment]
@uriva You need to provide height for the input

**Comment by uriva** [comment]
Ok, then the docs should mention that

**Comment by ElliottJRo** [comment]
@uriva this is a react native component styling doc issue rather than Native Base issue I think.

**Comment by SirNeuman** [comment]
It seems to be the `Item` wrapper which is limiting the height of the text input field, since the `numberOfLines` without the wrapper would increase the height of the field like normal. I'm not sure whether or not that is intended behavior, but it would be nice to set `numberOfLines` rather than specific height so the height changes dynamically based on font size inside the input field rather than a specific height.

**Comment by shivrajkumar** [comment]
The issue has been resolved for android in the latest version of NativeBase i.e, v2.2
For iOS, the issue seems to persist in react-native TextInput itself.
