### ISSUE TITLE
Change the <Header> color for different screens

### ISSUE THREAD

**Issue by AshwinTayson** [GeekyAnts/NativeBase#805]
This isn't a bug. But I want to if there is way to customize <Header> element's color based on which screen it is on. I used customisation to change it to black for home screen. I want blue for login screen, yellow for settings screen and so on.
`
<StyleProvider style={getTheme(myStyle)>`

can we something like 

```
set toolBarDefaultBg(color) 
  {
    toolBarDefaultBg: color
  },
```
Or is there any built-in way to accomplish this.

**Comment by GeekRishabh** [comment]
either you can create new variables for each page and use that in header by importing it and passing the it to below props
iosStatusbar="light-content"
androidStatusBarColor='blue' /instead of blue you can use commonColor.settingPageColor
where CommonColor is imported from ejected NB theme and settingPageColor is defined by you .
in header will work for you .

**Comment by SupriyaKalghatgi** [comment]
@AshwinTayson Solution by @GeekRishabh should work in this case
Closing this issue
